
title: Hassan Aziz Elnasri
author: Santa Monica College Student
email: aziz_elnasri_elsheik@student.smc.edu
description: > # this means to ignore newlines until "baseurl:"
To learn and grow through the natural sciences to improve the
challenges we face in society. One problem at a time.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
